frr version 10.2
frr defaults datacenter
hostname leaf4
log stdout
no ipv6 forwarding
!
interface lo
 ip address 10.255.1.4/32
!
interface eth1
 description to-spine1
 ip address 10.1.1.7/31
!
interface eth2
 description to-spine2
 ip address 10.1.2.7/31
!
interface eth3
 description to-server
 ip address 172.16.14.1/24
!
router bgp 65014
 bgp router-id 10.255.1.4
 bgp log-neighbor-changes
 no bgp ebgp-requires-policy
 bgp bestpath as-path multipath-relax
 neighbor FABRIC peer-group
 neighbor FABRIC remote-as external
 neighbor FABRIC advertisement-interval 0
 neighbor FABRIC timers 3 9
 neighbor 10.1.1.6  peer-group FABRIC
 neighbor 10.1.1.6  description spine1
 neighbor 10.1.2.6  peer-group FABRIC
 neighbor 10.1.2.6  description spine2
 !
 address-family ipv4 unicast
  network 10.255.1.4/32
  network 172.16.14.0/24
  neighbor FABRIC activate
  maximum-paths 64
 exit-address-family
!
line vty
